### ISSUE TITLE
Depth coarsely given

### ISSUE THREAD

**Issue by kojimano** [minosworld/minos#29]
Hi. While I was using the depth input, I realized the depth is given in a very coarse discretization rather than finely assigned to each point cloud. Is this because of dataset nature or the setting of the simulator? If this is the setting simulator how can I fix this? Thanks!!

**Comment by msavva** [comment]
@kojimano thanks for reporting this -- we resolved an issue which quantized depth output to 8-bit (equivalent to setting `encoding: binned` for the depth sensor), instead of respecting the actual `encoding:` parameter.  Now the default `encoding: depth` should provide full precision floating point depth.  Note that you will need to follow the installation steps again to build the updated server module.  Let us know if you still experience any problems

**Comment by kojimano** [comment]
Thank you!
