### ISSUE TITLE
The depth set to be 0.1 for the outside.

### ISSUE THREAD

**Issue by kojimano** [minosworld/minos#35]
It came across my experiment that the outside view is set to be the depth of 0.1, and this is pretty confusing for the perspective of the agent (admittingly there is some way to filter this using camera pose and etc on the user side). Is there any way to set this infinity instead of 0.1? Below is a snapshot of the online simulator which shows such an instance, but the recent gihub release shows the exact same behavior. (you can see the door connected to the outside has a very shallow depth.) Sorry if the issue is too specific but I thought it would be more convenient if this has been fixed.
![2018-03-24 14 32 22](https://user-images.githubusercontent.com/18011504/37867572-26fb05bc-2f71-11e8-9501-6723081c0c9f.png)

**Comment by msavva** [comment]
@kojimano thank you for reporting this issue.  We have pushed a version update that now properly returns zero values for parts of the image with no depth.  The case of no depth was being clamped to the camera near value (which is 0.1m by default) due to the depth buffer unpacking logic.  Please reinstall the minos server module and let us know if you still observe a problem.

**Comment by kojimano** [comment]
Looks like it is working good. Thank you!

**Comment by kojimano** [comment]
This issue seems to also happen as in Object Type as well. (The outside view or empty door is also categorized as a floor.)

**Comment by kojimano** [comment]
This issue seems to also happen as in Object Type as well. (The outside view or empty door is also categorized as a floor.)

**Comment by kojimano** [comment]
Misunderstanding. This issue never exists.
